In [ ]:
import os
os.system('pip install katonic-1.6.1-py3-none-any.whl')
from sklearn.model_selection import train_test_split
import pandas as pd
import pickle

import os
os.system('pip install katonic-1.6.1-py3-none-any.whl')
os.system('pip install optuna')
os.system('pip install boto3')
os.system('pip install plotly')

import numpy as np
from katonic.ml.client import set_exp
from katonic.ml.regression import Regressor
import plotly

In [2]:
with open('pickle_files/regressor_obj.pickle', 'rb') as f:
    regressor_obj = pickle.load(f)

In [3]:
logged_reg_models = regressor_obj.search_runs("32")
logged_reg_models

,artifact_uri,end_time,experiment_id,metrics.MAE,metrics.MSE,metrics.R2,metrics.RMSE,metrics.RMSLE,params.colsample_bytree,params.eta,...,start_time,status,tags.data_path,tags.experiment_id,tags.experiment_name,tags.features,tags.mlflow.log-model.history,tags.mlflow.parentRunId,tags.run_id,tags.version.mlflow
0,s3://models/32/1541143f60564ccfbb5e94abefd91e8...,2023-03-30 16:17:52.496000+00:00,32,17.344302,1993.669719,0.786213,44.650529,3.798866,None,None,...,2023-03-30 16:17:50.082000+00:00,FINISHED,/home/katonic/house_price_pipelines/Datasets/B...,32,house_price_prediction_katonic_sdk_pipeline,"['total_sqft', 'bath', 'BHK', '1st Block Jayan...","[{""run_id"": ""1541143f60564ccfbb5e94abefd91e8b""...",0d1c405388c44bfd81e1aa49d0717ca3,1541143f60564ccfbb5e94abefd91e8b,2.0.1
1,s3://models/32/ea01632f62654a518042e74cc348c65...,2023-03-30 16:17:50.051000+00:00,32,17.344302,1993.669719,0.786213,44.650529,3.798866,None,None,...,2023-03-30 16:17:47.469000+00:00,FINISHED,/home/katonic/house_price_pipelines/Datasets/B...,32,house_price_prediction_katonic_sdk_pipeline,"['total_sqft', 'bath', 'BHK', '1st Block Jayan...","[{""run_id"": ""ea01632f62654a518042e74cc348c650""...",0d1c405388c44bfd81e1aa49d0717ca3,ea01632f62654a518042e74cc348c650,2.0.1
2,s3://models/32/095607d0ad8f421f870ebc782d9039e...,2023-03-30 16:17:47.432000+00:00,32,17.344302,1993.669719,0.786213,44.650529,3.798866,None,None,...,2023-03-30 16:17:44.955000+00:00,FINISHED,/home/katonic/house_price_pipelines/Datasets/B...,32,house_price_prediction_katonic_sdk_pipeline,"['total_sqft', 'bath', 'BHK', '1st Block Jayan...","[{""run_id"": ""095607d0ad8f421f870ebc782d9039e3""...",0d1c405388c44bfd81e1aa49d0717ca3,095607d0ad8f421f870ebc782d9039e3,2.0.1
3,s3://models/32/ca4666880e614627a4d8434a04f30b5...,2023-03-30 16:17:44.917000+00:00,32,17.344302,1993.669719,0.786213,44.650529,3.798866,None,None,...,2023-03-30 16:17:42.369000+00:00,FINISHED,/home/katonic/house_price_pipelines/Datasets/B...,32,house_price_prediction_katonic_sdk_pipeline,"['total_sqft', 'bath', 'BHK', '1st Block Jayan...","[{""run_id"": ""ca4666880e614627a4d8434a04f30b58""...",0d1c405388c44bfd81e1aa49d0717ca3,ca4666880e614627a4d8434a04f30b58,2.0.1
4,s3://models/32/3d134af1a675444a8b6fb57c9bc2061...,2023-03-30 16:17:42.335000+00:00,32,17.344302,1993.669719,0.786213,44.650529,3.798866,None,None,...,2023-03-30 16:17:39.832000+00:00,FINISHED,/home/katonic/house_price_pipelines/Datasets/B...,32,house_price_prediction_katonic_sdk_pipeline,"['total_sqft', 'bath', 'BHK', '1st Block Jayan...","[{""run_id"": ""3d134af1a675444a8b6fb57c9bc20615""...",0d1c405388c44bfd81e1aa49d0717ca3,3d134af1a675444a8b6fb57c9bc20615,2.0.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
91,s3://models/32/b17c34d356f74196bb63bba8d9b5c29...,2023-03-30 10:33:32.137000+00:00,32,18.570586,1281.842194,0.854623,35.802824,3.578027,None,None,...,2023-03-30 10:33:28.832000+00:00,FINISHED,/home/katonic/Bengaluru_House_Data.csv,32,house_price_prediction_katonic_sdk_pipeline,"['total_sqft', 'bath', 'BHK', '1st Block Jayan...","[{""run_id"": ""b17c34d356f74196bb63bba8d9b5c294""...",659967f405f64411a3ff9b1d13adbdb2,b17c34d356f74196bb63bba8d9b5c294,2.0.1
92,s3://models/32/aae90702870744fcad2a55a20754c54...,2023-03-30 10:33:28.777000+00:00,32,18.570586,1281.842194,0.854623,35.802824,3.578027,None,None,...,2023-03-30 10:33:25.890000+00:00,FINISHED,/home/katonic/Bengaluru_House_Data.csv,32,house_price_prediction_katonic_sdk_pipeline,"['total_sqft', 'bath', 'BHK', '1st Block Jayan...","[{""run_id"": ""aae90702870744fcad2a55a20754c545""...",659967f405f64411a3ff9b1d13adbdb2,aae90702870744fcad2a55a20754c545,2.0.1
93,s3://models/32/5c79005c5a314b24bf85fc44a92bd7c...,2023-03-30 10:33:25.859000+00:00,32,18.570586,1281.842194,0.854623,35.802824,3.578027,None,None,...,2023-03-30 10:33:22.934000+00:00,FINISHED,/home/katonic/Bengaluru_House_Data.csv,32,house_price_prediction_katonic_sdk_pipeline,"['total_sqft', 'bath', 'BHK', '1st Block Jayan...","[{""run_id"": ""5c79005c5a314b24bf85fc44a92bd7c4""...",659967f405f64411a3ff9b1d13adbdb2,5c79005c5a314b24bf85fc44a92bd7c4,2.0.1
94,s3://models/32/659967f405f64411a3ff9b1d13adbdb...,2023-03-30 10:33:39.087000+00:00,32,18.570586,1281.842194,0.854623,35.802824,3.578027,None,None,...,2023-03-30 10:33:20.209000+00:00,FINISHED,/home/katonic/Bengaluru_House_Data.csv,32,house_price_prediction_katonic_sdk_pipeline,"['total_sqft', 'bath', 'BHK', '1st Block Jayan...","[{""run_id"": ""659967f405f64411a3ff9b1d13adbdb2""...",None,659967f405f64411a3ff9b1d13adbdb2,2.0.1
95,s3://models/32/18efdc72aa0a403697c7ca0d0b571f7...,2023-03-30 10:33:20.181000+00:00,32,18.570586,1281.842194,0.854623,35.802824,3.578027,None,None,...,2023-03-30 10:33:16.202000+00:00,FINISHED,/home/katonic/Bengaluru_House_Data.csv,32,house_price_prediction_katonic_sdk_pipeline,"['total_sqft', 'bath', 'BHK', '1st Block Jayan...","[{""run_id"": ""18efdc72aa0a403697c7ca0d0b571f7f""...",None,18efdc72aa0a403697c7ca0d0b571f7f,2.0.1

In [8]:
logged_reg_models = regressor_obj.search_runs("32")
rename_logged_models = logged_reg_models.rename(columns = {'metrics.MAE':'MAE','metrics.MSE':'MSE','metrics.R2':'R2','metrics.RMSE':'RMSE','metrics.RMSLE':'RMSLE','tags.experiment_name':'Experiment_name','tags.mlflow.parentRunId':'Parent_run_id'})
best_model_sort_r2 = rename_logged_models.sort_values(['R2'],ascending=False)
best_model_sort_r2 = best_model_sort_r2[:11]
best_model_sort_rmse = best_model_sort_r2.sort_values(['RMSE'],ascending=True).reset_index(drop=True)
best_model = best_model_sort_rmse['run_name'][0]
best_run_id = best_model_sort_rmse['Parent_run_id'][0]
best_model_sort_rmse

,artifact_uri,end_time,experiment_id,MAE,MSE,R2,RMSE,RMSLE,params.colsample_bytree,params.eta,...,start_time,status,tags.data_path,tags.experiment_id,Experiment_name,tags.features,tags.mlflow.log-model.history,Parent_run_id,tags.run_id,tags.version.mlflow
0,s3://models/32/901a5f4a16114819bec1e560e846c85...,2023-03-30 15:15:38.366000+00:00,32,15.061886,785.505507,0.916808,28.026871,3.333164,1,0.3,...,2023-03-30 15:15:34.172000+00:00,FINISHED,/home/katonic/house_price_pipelines/Datasets/B...,32,house_price_prediction_katonic_sdk_pipeline,"['Unnamed: 0', 'total_sqft', 'bath', 'BHK', '1...","[{""run_id"": ""901a5f4a16114819bec1e560e846c85c""...",2e34061b95464695b5fc46014b42e035,901a5f4a16114819bec1e560e846c85c,2.0.1
1,s3://models/32/2a3a25583ea74a63a7054d3524d8ddd...,2023-03-30 15:15:34.136000+00:00,32,15.061886,785.505507,0.916808,28.026871,3.333164,1,0.3,...,2023-03-30 15:15:29.684000+00:00,FINISHED,/home/katonic/house_price_pipelines/Datasets/B...,32,house_price_prediction_katonic_sdk_pipeline,"['Unnamed: 0', 'total_sqft', 'bath', 'BHK', '1...","[{""run_id"": ""2a3a25583ea74a63a7054d3524d8ddd9""...",2e34061b95464695b5fc46014b42e035,2a3a25583ea74a63a7054d3524d8ddd9,2.0.1
2,s3://models/32/528d7a7a468e4a14b82bce81fb5911b...,2023-03-30 15:15:29.644000+00:00,32,15.061886,785.505507,0.916808,28.026871,3.333164,1,0.3,...,2023-03-30 15:15:25.603000+00:00,FINISHED,/home/katonic/house_price_pipelines/Datasets/B...,32,house_price_prediction_katonic_sdk_pipeline,"['Unnamed: 0', 'total_sqft', 'bath', 'BHK', '1...","[{""run_id"": ""528d7a7a468e4a14b82bce81fb5911b6""...",2e34061b95464695b5fc46014b42e035,528d7a7a468e4a14b82bce81fb5911b6,2.0.1
3,s3://models/32/931de1238de84e7f8e862aa65a31c7b...,2023-03-30 15:15:25.571000+00:00,32,15.061886,785.505507,0.916808,28.026871,3.333164,1,0.3,...,2023-03-30 15:15:21.465000+00:00,FINISHED,/home/katonic/house_price_pipelines/Datasets/B...,32,house_price_prediction_katonic_sdk_pipeline,"['Unnamed: 0', 'total_sqft', 'bath', 'BHK', '1...","[{""run_id"": ""931de1238de84e7f8e862aa65a31c7b5""...",2e34061b95464695b5fc46014b42e035,931de1238de84e7f8e862aa65a31c7b5,2.0.1
4,s3://models/32/2e34061b95464695b5fc46014b42e03...,2023-03-30 15:15:42.510000+00:00,32,15.061886,785.505507,0.916808,28.026871,3.333164,None,None,...,2023-03-30 15:15:16.509000+00:00,FINISHED,/home/katonic/house_price_pipelines/Datasets/B...,32,house_price_prediction_katonic_sdk_pipeline,"['Unnamed: 0', 'total_sqft', 'bath', 'BHK', '1...","[{""run_id"": ""2e34061b95464695b5fc46014b42e035""...",None,2e34061b95464695b5fc46014b42e035,2.0.1
5,s3://models/32/333467a755034030817be2215fc8557...,2023-03-30 15:15:42.373000+00:00,32,15.061886,785.505507,0.916808,28.026871,3.333164,1,0.3,...,2023-03-30 15:15:38.400000+00:00,FINISHED,/home/katonic/house_price_pipelines/Datasets/B...,32,house_price_prediction_katonic_sdk_pipeline,"['Unnamed: 0', 'total_sqft', 'bath', 'BHK', '1...","[{""run_id"": ""333467a755034030817be2215fc8557e""...",2e34061b95464695b5fc46014b42e035,333467a755034030817be2215fc8557e,2.0.1
6,s3://models/32/b687e391193244f19ced55f7b254356...,2023-03-30 10:38:46.420000+00:00,32,18.120851,1161.145675,0.861623,34.075588,3.528581,None,None,...,2023-03-30 10:37:39.237000+00:00,FINISHED,/home/katonic/Bengaluru_House_Data.csv,32,house_price_prediction_katonic_sdk_pipeline,"['total_sqft', 'bath', 'BHK', '1st Block Jayan...","[{""run_id"": ""b687e391193244f19ced55f7b2543565""...",None,b687e391193244f19ced55f7b2543565,2.0.1
7,s3://models/32/6767a31bd0fe4f86ad2edca160e18bf...,2023-03-30 10:38:24.479000+00:00,32,18.146159,1161.844055,0.861540,34.085834,3.528882,None,None,...,2023-03-30 10:38:13.520000+00:00,FINISHED,/home/katonic/Bengaluru_House_Data.csv,32,house_price_prediction_katonic_sdk_pipeline,"['total_sqft', 'bath', 'BHK', '1st Block Jayan...","[{""run_id"": ""6767a31bd0fe4f86ad2edca160e18bf4""...",b687e391193244f19ced55f7b2543565,6767a31bd0fe4f86ad2edca160e18bf4,2.0.1
8,s3://models/32/c240eeac4b414649a2108cce548f192...,2023-03-30 10:38:13.493000+00:00,32,18.083279,1210.467617,0.855745,34.791775,3.549381,None,None,...,2023-03-30 10:38:02.460000+00:00,FINISHED,/home/katonic/Bengaluru_House_Data.csv,32,house_price_prediction_katonic_sdk_pipeline,"['total_sqft', 'bath', 'BHK', '1st Block Jayan...","[{""run_id"": ""c240eeac4b414649a2108cce548f192e""...",b687e391193244f19ced55f7b2543565,c240eeac4b414649a2108cce548f192e,2.0.1
9,s3://models/32/18efdc72aa0a403697c7ca0d0b571f7...,2023-03-30 10:33:20.181000+00:00,32,18.570586,1281.842194,0.854623,35.802824,3.578027,None,None,...,2023-03-30 10:33:16.202000+00:00,FINISHED,/home/katonic/Bengaluru_House_Data.csv,32,house_price_prediction_katonic_sdk_pipeline,"['total_sqft', 'bath', 'BHK', '1st Block Jayan...","[{""run_id"": ""18efdc72aa0a403697c7ca0d0b571f7f""...",None,18efdc72aa0a403697c7ca0d0b571f7f,2.0.1
10,s3://models/32/ceb1fe042b78490ea20124884f4f738...,2023-03-30 10:33:38.862000+00:00,32,18.570586,1281.842194,0.854623,35.802824,3.578027,None,None,...,2023-03-30 10:33:35.695000+00:00,FINISHED,/home/katonic/Bengaluru_House_Data.csv,32,house_price_prediction_katonic_sdk_pipeline,"['total_sqft', 'bath', 'BHK', '1st Block Jayan...","[{""run_id"": ""ceb1fe042b78490ea20124884f4f7381""...",659967f405f64411a3ff9b1d13adbdb2,ceb1fe042b78490ea20124884f4f7381,2.0.1

In [9]:
logged_model_url = best_model_sort_rmse['artifact_uri'][0]
logged_model = f'{logged_model_url}/{best_model}'
logged_model

's3://models/32/901a5f4a16114819bec1e560e846c85c/artifacts/house_price_prediction_katonic_sdk_pipeline_32_XGBoost_regression_tuned'

In [11]:
from katonic.ml.client import load_model

model = load_model(logged_model)

In [26]:
data = pd.read_csv('Feature_engineering.csv')
X=data.drop('price',axis='columns')
y=data.price

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)

In [13]:
preds = model.predict(X_test)

In [29]:
y_test_df = pd.DataFrame(y_test).reset_index(drop=True)
y_test_df['price_pred'] = preds

In [31]:
y_test_df.to_csv('/predictions.csv')