In [1]:
from sklearn.model_selection import train_test_split
import pandas as pd
import pickle
import numpy as np

import os
os.system('pip install katonic-1.6.1-py3-none-any.whl')
os.system('pip install optuna')
os.system('pip install boto3')
os.system('pip install plotly')

from katonic.ml.client import set_exp
from katonic.ml.regression import Regressor
import plotly

In [3]:
data = pd.read_csv('Feature_engineering.csv')
data = data.drop('Unnamed: 0',axis=1)

In [4]:
X=data.drop('price',axis='columns')
y=data.price

In [5]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)

In [6]:
regressor = Regressor(
    X_train,
    X_test,
    y_train,
    y_test,
    experiment_name="house_price_prediction_katonic_sdk_pipeline",
    source_name="House_Price_pred_mlflow_sdk_test.ipynb", # /home/katonic/model-cluster-backup/
    features=X_train.columns.to_list(),
    artifacts={"data_path": "/home/katonic/house_price_pipelines/Bengaluru_House_Data.csv",}
)

In [7]:
pickle_out = open("regressor_obj.pickle","wb")
pickle.dump(regressor, pickle_out)

In [3]:
import pickle
with open('regressor_obj.pickle', 'rb') as f:
    regressor_obj = pickle.load(f)

In [6]:
regressor_obj.search_runs("32")

,artifact_uri,end_time,experiment_id,metrics.MAE,metrics.MSE,metrics.R2,metrics.RMSE,metrics.RMSLE,params.colsample_bytree,params.eta,...,start_time,status,tags.data_path,tags.experiment_id,tags.experiment_name,tags.features,tags.mlflow.log-model.history,tags.mlflow.parentRunId,tags.run_id,tags.version.mlflow
0,s3://models/32/1541143f60564ccfbb5e94abefd91e8...,2023-03-30 16:17:52.496000+00:00,32,17.344302,1993.669719,0.786213,44.650529,3.798866,None,None,...,2023-03-30 16:17:50.082000+00:00,FINISHED,/home/katonic/house_price_pipelines/Datasets/B...,32,house_price_prediction_katonic_sdk_pipeline,"['total_sqft', 'bath', 'BHK', '1st Block Jayan...","[{""run_id"": ""1541143f60564ccfbb5e94abefd91e8b""...",0d1c405388c44bfd81e1aa49d0717ca3,1541143f60564ccfbb5e94abefd91e8b,2.0.1
1,s3://models/32/ea01632f62654a518042e74cc348c65...,2023-03-30 16:17:50.051000+00:00,32,17.344302,1993.669719,0.786213,44.650529,3.798866,None,None,...,2023-03-30 16:17:47.469000+00:00,FINISHED,/home/katonic/house_price_pipelines/Datasets/B...,32,house_price_prediction_katonic_sdk_pipeline,"['total_sqft', 'bath', 'BHK', '1st Block Jayan...","[{""run_id"": ""ea01632f62654a518042e74cc348c650""...",0d1c405388c44bfd81e1aa49d0717ca3,ea01632f62654a518042e74cc348c650,2.0.1
2,s3://models/32/095607d0ad8f421f870ebc782d9039e...,2023-03-30 16:17:47.432000+00:00,32,17.344302,1993.669719,0.786213,44.650529,3.798866,None,None,...,2023-03-30 16:17:44.955000+00:00,FINISHED,/home/katonic/house_price_pipelines/Datasets/B...,32,house_price_prediction_katonic_sdk_pipeline,"['total_sqft', 'bath', 'BHK', '1st Block Jayan...","[{""run_id"": ""095607d0ad8f421f870ebc782d9039e3""...",0d1c405388c44bfd81e1aa49d0717ca3,095607d0ad8f421f870ebc782d9039e3,2.0.1
3,s3://models/32/ca4666880e614627a4d8434a04f30b5...,2023-03-30 16:17:44.917000+00:00,32,17.344302,1993.669719,0.786213,44.650529,3.798866,None,None,...,2023-03-30 16:17:42.369000+00:00,FINISHED,/home/katonic/house_price_pipelines/Datasets/B...,32,house_price_prediction_katonic_sdk_pipeline,"['total_sqft', 'bath', 'BHK', '1st Block Jayan...","[{""run_id"": ""ca4666880e614627a4d8434a04f30b58""...",0d1c405388c44bfd81e1aa49d0717ca3,ca4666880e614627a4d8434a04f30b58,2.0.1
4,s3://models/32/3d134af1a675444a8b6fb57c9bc2061...,2023-03-30 16:17:42.335000+00:00,32,17.344302,1993.669719,0.786213,44.650529,3.798866,None,None,...,2023-03-30 16:17:39.832000+00:00,FINISHED,/home/katonic/house_price_pipelines/Datasets/B...,32,house_price_prediction_katonic_sdk_pipeline,"['total_sqft', 'bath', 'BHK', '1st Block Jayan...","[{""run_id"": ""3d134af1a675444a8b6fb57c9bc20615""...",0d1c405388c44bfd81e1aa49d0717ca3,3d134af1a675444a8b6fb57c9bc20615,2.0.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
91,s3://models/32/b17c34d356f74196bb63bba8d9b5c29...,2023-03-30 10:33:32.137000+00:00,32,18.570586,1281.842194,0.854623,35.802824,3.578027,None,None,...,2023-03-30 10:33:28.832000+00:00,FINISHED,/home/katonic/Bengaluru_House_Data.csv,32,house_price_prediction_katonic_sdk_pipeline,"['total_sqft', 'bath', 'BHK', '1st Block Jayan...","[{""run_id"": ""b17c34d356f74196bb63bba8d9b5c294""...",659967f405f64411a3ff9b1d13adbdb2,b17c34d356f74196bb63bba8d9b5c294,2.0.1
92,s3://models/32/aae90702870744fcad2a55a20754c54...,2023-03-30 10:33:28.777000+00:00,32,18.570586,1281.842194,0.854623,35.802824,3.578027,None,None,...,2023-03-30 10:33:25.890000+00:00,FINISHED,/home/katonic/Bengaluru_House_Data.csv,32,house_price_prediction_katonic_sdk_pipeline,"['total_sqft', 'bath', 'BHK', '1st Block Jayan...","[{""run_id"": ""aae90702870744fcad2a55a20754c545""...",659967f405f64411a3ff9b1d13adbdb2,aae90702870744fcad2a55a20754c545,2.0.1
93,s3://models/32/5c79005c5a314b24bf85fc44a92bd7c...,2023-03-30 10:33:25.859000+00:00,32,18.570586,1281.842194,0.854623,35.802824,3.578027,None,None,...,2023-03-30 10:33:22.934000+00:00,FINISHED,/home/katonic/Bengaluru_House_Data.csv,32,house_price_prediction_katonic_sdk_pipeline,"['total_sqft', 'bath', 'BHK', '1st Block Jayan...","[{""run_id"": ""5c79005c5a314b24bf85fc44a92bd7c4""...",659967f405f64411a3ff9b1d13adbdb2,5c79005c5a314b24bf85fc44a92bd7c4,2.0.1
94,s3://models/32/659967f405f64411a3ff9b1d13adbdb...,2023-03-30 10:33:39.087000+00:00,32,18.570586,1281.842194,0.854623,35.802824,3.578027,None,None,...,2023-03-30 10:33:20.209000+00:00,FINISHED,/home/katonic/Bengaluru_House_Data.csv,32,house_price_prediction_katonic_sdk_pipeline,"['total_sqft', 'bath', 'BHK', '1st Block Jayan...","[{""run_id"": ""659967f405f64411a3ff9b1d13adbdb2""...",None,659967f405f64411a3ff9b1d13adbdb2,2.0.1
95,s3://models/32/18efdc72aa0a403697c7ca0d0b571f7...,2023-03-30 10:33:20.181000+00:00,32,18.570586,1281.842194,0.854623,35.802824,3.578027,None,None,...,2023-03-30 10:33:16.202000+00:00,FINISHED,/home/katonic/Bengaluru_House_Data.csv,32,house_price_prediction_katonic_sdk_pipeline,"['total_sqft', 'bath', 'BHK', '1st Block Jayan...","[{""run_id"": ""18efdc72aa0a403697c7ca0d0b571f7f""...",None,18efdc72aa0a403697c7ca0d0b571f7f,2.0.1