In [7]:
from sklearn.model_selection import train_test_split
import pandas as pd
import pickle
import numpy as np

import os
os.system('pip install katonic-1.6.1-py3-none-any.whl[ml]')
os.system('pip install plotly')

from katonic.ml.client import set_exp
from katonic.ml.regression import Regressor
import plotly

In [8]:
data = pd.read_csv('Feature_engineering.csv')
data

,Unnamed: 0,total_sqft,bath,price,BHK,1st Block Jayanagar,1st Phase JP Nagar,2nd Phase Judicial Layout,2nd Stage Nagarbhavi,5th Block Hbr Layout,...,Vijayanagar,Vishveshwarya Layout,Vishwapriya Layout,Vittasandra,Whitefield,Yelachenahalli,Yelahanka,Yelahanka New Town,Yelenahalli,Yeshwanthpur
0,0,2850.0,4.0,428.0,4,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1,1630.0,3.0,194.0,3,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,2,1875.0,2.0,235.0,3,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,3,1200.0,2.0,130.0,3,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,4,1235.0,2.0,148.0,2,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7234,10233,1200.0,2.0,70.0,2,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7235,10234,1800.0,1.0,200.0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7236,10237,1353.0,2.0,110.0,2,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7237,10238,812.0,1.0,26.0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7238,10241,3600.0,5.0,400.0,4,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [9]:
# Splitting the Dataset.

X=data.drop('price',axis='columns')
y=data.price

#### Split the dataset into training and validation sets

In [10]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)

In [4]:
exp_name = "house_price_prediction_katonic_sdk_pipeline"

In [5]:
artifacts = {
    "data_path": "/home/katonic/house_price_pipelines/Datasets/Bengaluru_House_Data.csv",
}

In [11]:
regressor = Regressor(
    X_train,
    X_test,
    y_train,
    y_test,
    experiment_name=exp_name,
    source_name="House_Price_pred_mlflow_sdk_test.ipynb", # /home/katonic/model-cluster-backup/
    features=X_train.columns.to_list(),
    artifacts=artifacts,
)

In [13]:
parames = {
   'max_depth':[6,7,10,50,100],
    'eta':.3,
    'subsample': 1,
    'colsample_bytree': 1,

}

xgb_model = regressor.XGBRegressor(is_tune = True, params = parames)

[I 2023-03-30 15:15:21,460] A new study created in memory with name: no-name-85f06a1b-b431-4740-bde4-6f4c20bd223e
[I 2023-03-30 15:15:25,599] Trial 0 finished with value: 0.9168076898964554 and parameters: {'eta': 0.3, 'subsample': 1, 'colsample_bytree': 1}. Best is trial 0 with value: 0.9168076898964554.
[I 2023-03-30 15:15:29,680] Trial 1 finished with value: 0.9168076898964554 and parameters: {'eta': 0.3, 'subsample': 1, 'colsample_bytree': 1}. Best is trial 0 with value: 0.9168076898964554.
[I 2023-03-30 15:15:34,168] Trial 2 finished with value: 0.9168076898964554 and parameters: {'eta': 0.3, 'subsample': 1, 'colsample_bytree': 1}. Best is trial 0 with value: 0.9168076898964554.
[I 2023-03-30 15:15:38,397] Trial 3 finished with value: 0.9168076898964554 and parameters: {'eta': 0.3, 'subsample': 1, 'colsample_bytree': 1}. Best is trial 0 with value: 0.9168076898964554.
[I 2023-03-30 15:15:42,402] Trial 4 finished with value: 0.9168076898964554 and parameters: {'eta': 0.3, 'subsample': 1, 'colsample_bytree': 1}. Best is trial 0 with value: 0.9168076898964554.

Number of finished trials:  5
Best trial:
  R2:  0.9168076898964554
  Params:
    eta: 0.3
    subsample: 1
    colsample_bytree: 1

In [ ]:
pickle_out = open("xgb_regressor.pickle","wb")
pickle.dump(xgb_model, pickle_out)